### PR TITLE
Update requests-toolbelt dependency

### PR DESCRIPTION
**Pull request by flore2003**
Update requests-toolbelt dependency to be compatible with requests-toolbelt version ^1.0.0

### CODE REVIEW

**Comment by flore2003** [comment]
Is there a reason why poetry is pinned to 1.1.2 in the CI? I think that is the reason why the install fails.

**Comment by schehata** [comment]
hi @flore2003 , just saw your PR, I am working on another to update deps and noticed the error, I am going to upgrade poetry to 1.5, lets see if that fixes it.

**Comment by schehata** [comment]
depends_on #66

**Comment by flore2003** [comment]
CI still fails. From the first look, this does not seem to be a problem with this change, but I might be mistaken.

**Comment by schehata** [comment]
> CI still fails. From the first look, this does not seem to be a problem with this change, but I might be mistaken.

hmm, looks like it happens because doesn't have access to the integ secrets, I create #73 to disable this test on forks. I will merge the other dependabot PRs, so there might be conflicts again the pyproject.toml, sorry for the inconvenice.

**Pull request merged**
